### ISSUE TITLE
pycuda 0.94 requirement

### ISSUE THREAD

**Issue by lebedov** [fjarri-attic/pyfft#4]
It might be advisable to mention in the module docs that pycuda 0.94 is required by pyfft; some of the constructs invoked by pyfft don't exist in pycuda 0.93.

**Comment by fjarri** [comment]
Yes, but I am not sure documentation is the perfect place for this - because, the chances are, one will first install the module and run the tests without looking at the docs.

Added a warning anyway - http://github.com/Manticore/pyfft/commit/4febaffa49fe0b0d3075d59d26d6306e35f8856b . And I will try to make the module compatible with 0.93 (if it does not lead to changes in interface).
